name: Deploy Wazuh Rules

on:
  push:
    paths:
      - 'detections/wazuh-rules/*.xml'
      - 'detections/decoders/*.xml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: setup/wazuh/tf-deployment
        run: terraform init

      - name: Terraform Apply
        working-directory: setup/wazuh/tf-deployment
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
